import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog app 10-01-2023</title>
        <meta name="description" content="Generated by me" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center">Hey baby! </h1>
      </main>
    </>
  );
}
